### ISSUE TITLE
Saigo Player exits when back button is pressed and crashes when a song is played on relaunch.

### ISSUE THREAD

**Issue by kodeblacc** [its-wufu/SimpleMp3Player#1]
#### Expected behavior
As is most music players, it is expected that the back navigation button doesn't totally exit the music player and even if it does exit the player, it'll be possible to always reopen and play music with it.
#### Actual behavior
Pressing the hardware(device) back navigation button while on the music player interface exits the app and an attempt to start the app again and play music again unfortunately caused the software to crash.
#### How to reproduce
- launch software
- play a song
- press device back navigation button(the app will stop)
- relaunch the app and play a song( the app crashes)<hr>
* App name/App version: Saigo Player  v1.2.7
* Operating system:  Android 7.0
#### Recording Of The Bug
https://youtu.be/1JZivDQg-ZY

#### Logcat 
```
FATAL EXCEPTION: main
Process: saigokyo.simplemp3player, PID: 2721
java.lang.IllegalStateException
	at android.media.MediaPlayer._reset(Native Method)
	at android.media.MediaPlayer.reset(MediaPlayer.java:1746)
	at saigokyo.simplemp3player.Main.playSong(Main.java:817)
	at saigokyo.simplemp3player.Main.onListItemClick(Main.java:771)
	at android.app.ListActivity$2.onItemClick(ListActivity.java:319)
	at android.widget.AdapterView.performItemClick(AdapterView.java:315)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1204)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3309)
	at android.widget.AbsListView$3.run(AbsListView.java:4378)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
```

**Comment by its-wufu** [comment]
I can reproduce the issue and will take a look at it. Thank you so much for your efford again !
I can update you, when I know more :)

**Comment by its-wufu** [comment]
So that would be fixed too. Thank you again for submitting these issues. The backpress Button really should not close the app like that. The new release version is uploading right now.
