### ISSUE TITLE
The music play crashed when the previous button was pressed and the track was played from playlist menu.

### ISSUE THREAD

**Issue by kodeblacc** [its-wufu/SimpleMp3Player#2]
#### Expected behavior
The previous button of a music player plays the previous song on a queue. This function should work properly from any menu on the music play so far the button is available
#### Actual behavior
After creating a playlist and playing a song from the playlist menu, pressing the previous button caused the music player to crash.
#### How to reproduce
- Launch the app
- Add song to playlist
- Play a song from playlist menu 
- Press the the previous button

#### Test Enviroment
* Device: Tecno Camon CM
* Operating system: Android 7.0

#### Recording of the bug
https://youtu.be/CYh3xFODkNU

#### Logcat 

```
FATAL EXCEPTION: main
Process: saigokyo.simplemp3player, PID: 21323
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.get(ArrayList.java:413)
	at saigokyo.simplemp3player.Main.prevSong(Main.java:993)
	at saigokyo.simplemp3player.Main$4.onClick(Main.java:338)
	at android.view.View.performClick(View.java:6076)
	at android.view.View$PerformClick.run(View.java:23138)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
```

**Comment by its-wufu** [comment]
That is really helpful, thank you very much! Until recently I wasn't aware, that people acually post issues in this repository. So now I had some time to look into the issue and I think I have fixed it. 
So I will upload the fixed version later today.
Thank you again for your efford!
